# Generated by Django 3.2.5 on 2021-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0003_auto_20210710_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createDat',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
