# Generated by Django 3.2.5 on 2021-09-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0005_shippingaddress_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_product.cart'),
        ),
    ]
