# Generated by Django 3.2.5 on 2021-07-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0005_auto_20210713_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
