# Generated by Django 3.2.5 on 2021-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0009_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dicount',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(1, 'Buyurtma qabul qilindi'), (2, 'Buyurtmani qayta ishlash'), (3, "Yo'lda"), (4, 'Buyurtma bajarildi'), (5, 'Buyurtma bekor qilindi')], default=1, max_length=250),
        ),
    ]
