# Generated by Django 3.2.5 on 2021-09-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0011_auto_20210928_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dicount',
            new_name='discount',
        ),
    ]
