# Generated by Django 3.2.5 on 2021-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0012_rename_dicount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Buyurtma qabul qilindi', 'Buyurtma qabul qilindi'), ('Buyurtmani qayta ishlash', 'Buyurtmani qayta ishlash'), ("Yo'lda", "Yo'lda"), ('Buyurtma bajarildi', 'Buyurtma bajarildi'), ('Buyurtma bekor qilindi', 'Buyurtma bekor qilindi')], default=1, max_length=250),
        ),
    ]
