# Generated by Django 3.2.5 on 2021-09-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0014_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartproduct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_product.cartproduct'),
        ),
    ]
