# Generated by Django 3.2.5 on 2021-09-28 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_product', '0016_remove_order_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_numbr', models.IntegerField(max_length=16, verbose_name='Karta nomeri')),
                ('carta_data', models.IntegerField(max_length=5, verbose_name='Karta mudati')),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_product.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
