# Generated by Django 3.2.5 on 2021-10-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0019_alter_order_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartproduct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_product.cartproduct'),
        ),
    ]
