# Generated by Django 3.2.5 on 2021-10-05 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0021_remove_order_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payme',
            name='id',
        ),
        migrations.AlterField(
            model_name='payme',
            name='carta_numbr',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Karta nomeri'),
        ),
    ]
